### ISSUE TITLE
cannot build Spiral on a system without GPU

### ISSUE THREAD

**Issue by petermcLBL** [spiral-software/spiral-software#38]
I am running on a system without GPU support.  When I update the `develop` branch of Spiral and do `cmake ..` in a subdirectory, I get:
```
-- Cmake version = 3.18, using FindCUDAToolkit module
-- CUDA Toolkit Found : Version = 11.3.109
-- The CUDA compiler identification is unknown
CMake Error at support/CMakeLists.txt:46 (project):
  No CMAKE_CUDA_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CUDACXX" or the CMake cache entry CMAKE_CUDA_COMPILER to the full
  path to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
```
I used to be able to build on this system with `cmake -D_codegen=CPU ..`, but that doesn't help anymore.  I get the same error as above.

The Spiral installation instructions say: "_A number of the tests and examples in the release require a GPU in order to work. If the system you are building for has no GPU support (i.e., no CUDA toolkit is installed) these examples/tests will be skipped._"

**Comment by broderickpt** [comment]
Not an issue.  CMake was finding a CUDA installation, however, the nvcc executable was not in the PATH.
